### ISSUE TITLE
Not having a binary is confusing in the command-line utilities category on crates.io

### ISSUE THREAD

**Issue by carols10cents** [fangyuanziti/which-rs#4]
Hi! Someone recently contacted the crates.io team and mentioned that the `which` crate was confusing. They found it in the [command-line utilities category](https://crates.io/categories/command-line-utilities) and tried to run `cargo install which`, but since `which` doesn't have a binary, it didn't work.

I get that the `which` crate provides the same information that the unix `which` tool does, so it's not *wrong* to have it in the command-line utilities category, but it is a little confusing. Some possible ways to make it less confusing:

- Add a src/main.rs so that the `which` crate *is* installable and usable as a command-line utility
- Choose a different category than command-line utilities

Just some suggestions!

**Comment by fangyuanziti** [comment]
Thanks for your suggestions. I will change the category. : smail:

**Comment by fangyuanziti** [comment]
Change the category into `os` and `filesystem`. Update the version already.
