### ISSUE TITLE
support more than just .exe files on Windows

### ISSUE THREAD

**Issue by jokeyrhyme** [fangyuanziti/which-rs#7]
Hi, great library, very handy!

I've noticed that it doesn't find .bat, .cmd, or .com files on Windows

There are quite a lot of executable file extensions on Windows, and my specific use case requires finding .cmd files

**Comment by jokeyrhyme** [comment]
Hmmm, might be related to this https://github.com/rust-lang/rust/issues/37519

**Comment by fangyuanziti** [comment]
I will find a time to implement this. Of course, the PR is also appreciated.

**Comment by fangyuanziti** [comment]
closed by #8 . Thanks @WLBF 's work.

**Comment by jokeyrhyme** [comment]
Oh, yay! Thanks! <3
